
import type { Deal } from './types';

export const mockDeals: Deal[] = [
    {
      dealId: '1',
      name: 'Profitable Shopify CRM SaaS',
      industry: 'B2B SaaS',
      location: 'Remote',
      sde: 250000,
      askingPrice: 1125000,
      multiple: 4.5,
      growth: 0.25,
      tenure: 4,
      signal: "Boutique CRM for Shopify stores with a solid MRR base and low churn. Two strategic acquirers have already shown interest.",
      source: 'MicroAcquire',
      sourceUrl: '#',
      type: 'listed',
      isPro: true,
      listedAt: '1 day ago'
    },
    {
      dealId: '2',
      name: 'Austin Lawn Care Co.',
      industry: 'Landscaping',
      location: 'Austin, TX',
      sde: 280000,
      askingPrice: 1100000,
      multiple: 3.9,
      growth: 0.32,
      tenure: 8,
      signal: "Owner posted 'exploring my next chapter' on LinkedIn. Business has a strong local reputation and recurring revenue.",
      source: 'LinkedIn',
      sourceUrl: '#',
      type: 'off-market',
      isPro: true,
      listedAt: '2 days ago'
    },
    {
      dealId: '3',
      name: 'Denver Plumbing Services',
      industry: 'Plumbing',
      location: 'Denver, CO',
      sde: 450000,
      askingPrice: 1500000,
      multiple: 3.3,
      growth: 0.15,
      tenure: 12,
      signal: "Listed on BizBuySell with verified financials. Stable business with a large customer base and skilled team in place.",
      source: 'BizBuySell',
      sourceUrl: '#',
      type: 'listed',
      isPro: true,
      listedAt: '1 day ago'
    },
    {
      dealId: '4',
      name: 'DFW Commercial Cleaning',
      industry: 'Cleaning',
      location: 'Dallas-Fort Worth, TX',
      sde: 180000,
      askingPrice: 550000,
      multiple: 3.1,
      growth: 0.18,
      tenure: 6,
      signal: "Long-standing commercial cleaning business with multi-year contracts. A solid, reliable cash-flow opportunity.",
      source: 'BizBuySell',
      sourceUrl: '#',
      type: 'listed',
      isPro: false, // Make one deal available for free users
      listedAt: '5 days ago'
    },
     {
      dealId: '5',
      name: 'Niche E-commerce Subscription Box',
      industry: 'E-commerce',
      location: 'Remote',
      sde: 150000,
      askingPrice: 600000,
      multiple: 4.0,
      growth: 0.45,
      tenure: 3,
      signal: "Featured on MicroAcquire. Fast-growing subscription box service in a popular hobby niche. High customer retention.",
      source: 'MicroAcquire',
      sourceUrl: '#',
      type: 'listed',
      isPro: true,
      listedAt: '3 days ago'
    },
    {
      dealId: '6',
      name: 'Mobile App for Fitness Tracking',
      industry: 'SaaS',
      location: 'Remote',
      sde: 90000,
      askingPrice: 450000,
      multiple: 5.0,
      growth: 0.60,
      tenure: 2,
      signal: "Explosive user growth over the last 6 months. Owner is a developer moving on to a new project.",
      source: 'MicroAcquire',
      sourceUrl: '#',
      type: 'listed',
      isPro: true,
      listedAt: '6 days ago'
    }
  ];
